@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name" : "Felipe",
  "email": "Felipe1@example.com",
  "password": "123456",
  "role":"ADMIN"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "Felipe@example.com",
  "password": "123456"
}

###

# @name create_budget
POST {{baseUrl}}/budgets
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "NewBudget"
}

###

# @name fetch_budget
GET {{baseUrl}}/budgets
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "New Account",
  "budgetId":"8226d6c9-3287-4d61-9b6b-d8346734b7ad",
  "balance":0
}

###

# @name create_transaction
POST {{baseUrl}}/transactions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "description":"First Transaction",
  "type":"EXPENSES",
  "budgetId":"8226d6c9-3287-4d61-9b6b-d8346734b7ad",
  "amount":100,
  "accountId":"42e5e08a-c81b-43f1-a9fa-9b0af9886d94",
  "date":"2024-10-04",
  "categoryId":"165a82f9-ba7c-42d8-95fa-09d822df5dad"
}

###

# @name create_category
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name":"New Category EXPENSES",
  "type":"EXPENSES",
  "budgetId":"8226d6c9-3287-4d61-9b6b-d8346734b7ad"
}